name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hugging Face Hub CLI
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub[cli]

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_REPO: ${{ secrets.SPACE_REPO }}
        run: |
          set -e
          
          # Default to <github user>/<repo name> if SPACE_REPO not provided
          if [ -z "$SPACE_REPO" ]; then
            SPACE_REPO="${{ github.repository }}"
          fi
          
          echo "Using Space repository: $SPACE_REPO"
          
          # Create the Space if it does not exist
          huggingface-cli repo create "$SPACE_REPO" --type space --space-sdk docker -y || true

          # Push all files to the Space
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space "https://huggingface:$HF_TOKEN@huggingface.co/$SPACE_REPO" || true
          git push space HEAD:main --force 