name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hugging Face Hub CLI
        run: |
          python -m pip install --upgrade pip
          # Install a recent version that supports --space-sdk
          pip install "huggingface_hub[cli]==0.25.0"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_REPO: ${{ secrets.SPACE_REPO }}
        run: |
          set -e
          if [ -z "$SPACE_REPO" ]; then SPACE_REPO="${{ github.repository }}"; fi
          echo "Using Space repository: $SPACE_REPO"
          
          # No creation step needed – Space already exists
          
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"
          git remote add space "https://huggingface:$HF_TOKEN@huggingface.co/$SPACE_REPO" || true
          git push space HEAD:main --force 