name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Hugging Face Hub CLI
        run: |
          python -m pip install --upgrade pip
          # Install a recent version that supports --space-sdk
          pip install "huggingface_hub[cli]==0.25.0"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_REPO: ${{ secrets.SPACE_REPO }}
        run: |
          set -e
          
          # Default to <github user>/<repo name> if SPACE_REPO not provided
          if [ -z "$SPACE_REPO" ]; then
            SPACE_REPO="${{ github.repository }}"
          fi
          
          echo "Using Space repository: $SPACE_REPO"
          
          # Attempt to create the Space as a Docker Space using modern flags
          if ! huggingface-cli repo create "$SPACE_REPO" --repo-type space --space-sdk docker -y 2>/dev/null; then
            echo "Falling back to legacy flags (deprecated)."
            if ! huggingface-cli repo create "$SPACE_REPO" --type space --space-sdk docker -y 2>/dev/null; then
              echo "Unable to create Space with Docker SDK; creating default Space."
              huggingface-cli repo create "$SPACE_REPO" --repo-type space -y || true
            fi
          fi

          # Push all files to the Space
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space "https://huggingface:$HF_TOKEN@huggingface.co/$SPACE_REPO" || true
          git push space HEAD:main --force 